config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :articles do
    resource :vote, module: :articles
  end
  resources :categories

  resource :session, only: %i[new create destroy]
  get 'signin' => 'sessions#new'

  resources :users
  get 'signup' => 'users#new'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  before_save :set_slug
  has_many :categorizations, dependent: :destroy
  has_many :articles, through: :categorizations, dependent: :destroy

  validates :name, :priority, presence: true
  validates :name, length: { minimum: 5, maximum: 10 }, uniqueness: true

  scope :category_order, -> { Category.order(priority: :asc) }

  def most_recent_article
    articles = self.articles.order(created_at: :desc)
    articles[0]
  end

  def articles_order
    articles.order(created_at: :desc)
  end

  def to_param
    slug
  end

  private

  def set_slug
    self.slug = name.parameterize
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_signin, except: %i[index show]

  def index
    @categories = Category.category_order
    @categories_in_box = @categories.slice(0, 4)
    @most_voted_article = Article.most_voted_article
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @category = Category.find_by!(slug: params[:id])
    @articles = @category.articles_order
    @row_count = (@articles.length / 2.0).ceil
  end

  private

  def set_category
    @category = Category.find_by!(slug: params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  private

  def category_background(category)
    if category.most_recent_article
      cloudinary_url(category.most_recent_article.image.key, width: 400, crop: :scale)
    else
      'https://images.unsplash.com/photo-1573164574001-518958d9baa2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80'
    end
  end

  def article_image(article, width = 400)
    if article
      cloudinary_url(article.image.key, width: width, crop: :scale)
    else
      'https://images.unsplash.com/photo-1573164574001-518958d9baa2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80'
    end
  end

  def category_article1(articles, count)
    articles[2 * count]
  end

  def category_article2(articles, count)
    articles[2 * count + 1]
  end
end

app/views/categories/_article_card.html.erb
<div class="article-card">
    <div class="image-container w-50" style="background-image: linear-gradient(0deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.2) 15%, rgba(0,0,0,0.2) 85%, rgba(0,0,0,0.5) 100%), url(<%= article_image(article) %>)">
    
    </div>
    <div class="text-container w-50">
        <div class="container-top">
        <h4 class="mb-3"><span class="category-name"><%= (category).capitalize %></span></h4>
            <h5><%= article.title %></h5>
            <p><%= truncate(article.text, length: 100) %></p>
        </div>
        <section class="container-bottom">
            <p class="mb-0 author-name">Author: <%= article.author.name %></p>
            <div id="votes">
                <%= vote?(current_user, article) %> <span class='vote-count ml-2'><%= pluralize(article.votes.length, "Vote") %></span>
            </div>
        </section>
    </div>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>

    <%= render "shared/errors", object: category %>
    <div class="form-group"> 
        <%= form.label :name %>
        <%= form.text_field :name, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group my-3">
        <%= form.label :priority, class: 'mr-3' %>    
        <%= form.select(:priority, [["High", 1], ["Medium", 2], ["Low", 3]], class: "form-control" )%>
    </div>
    
    <%= form.submit "Submit", class: 'create' %>
<% end %>

app/views/categories/index.html.erb
<div class="home">
    
    <div class="top-article" style="background-image: linear-gradient(0deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.4) 15%, rgba(0,0,0,0.2) 85%, rgba(0,0,0,0.5) 100%), url(<%= article_image(@most_voted_article, 1200) %>)">
        <% if @most_voted_article %>
            <h5 class="title"><%= @most_voted_article.title %></h5>
            <p class="description"><%= truncate(@most_voted_article.text, length: 200) %></p>
        <% end %>
    </div>

    <div class="category-list">
        <% @categories_in_box.each do |category| %>
            <div class="category-box" style="background-image: linear-gradient(0deg, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.2) 15%, rgba(0,0,0,0.2) 85%, rgba(0,0,0,0.5) 100%), url(<%= category_background(category) %>)">
                <h5 class="mr-2"><%= link_to (category.name).capitalize, category_path(category), class: "category-name" %></h5>
                <p class="title"><%= category.most_recent_article&.title %></p>
            </div>  
        <% end %>
    </div>
</div>

app/views/categories/new.html.erb
<div class="static-background">
    <div class="form-container">
        <h3>Add New Category</h3>
        <%= render 'form', category: @category %>
    </div>
</div>

app/views/categories/show.html.erb
<div class="category-article-list">
    <% if @articles.length > 0 %>
        <% @row_count.times do |count| %>
        
            <div class="article-row <%= count.even? ? "even" : "odd" %>">
                <%= render "article_card", article: category_article1(@articles, count), category: @category.name %>
                <% if category_article2(@articles, count) %>
                    <%= render "article_card", article: category_article2(@articles, count), category: @category.name %>
                <% end %>
            </div>
        <% end %>
    <% else %>
        <h3>Please Add some Articles</h3>
    <% end %>

</div>