config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :articles do
    resource :vote, module: :articles
  end
  resources :categories

  resource :session, only: %i[new create destroy]
  get 'signin' => 'sessions#new'

  resources :users
  get 'signup' => 'users#new'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
    <div class="notice flash">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert flash">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<% if false %>
<div class="navbar navbar-expand-lg navbar-light bg-light px-2 d-flex align-items-center">
    
    <div class="d-flex justify-content-between align-items-center w-100 flex-lg-row" >
        <%= link_to "herSTYLE", root_path, class: "navbar-brand" %>
    
        <div class="flex-2 d-flex justify-content-center align-items-center">
            <ul class="navbar-nav">
                <li class="nav-item active px-lg-2">
                    <%= link_to "Privacy Policy", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item active px-lg-2">
                    <%= link_to "Terms & Conditions", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item active px-lg-2">
                    <p class="mb-0 nav-link">Copyright 2020. All right reserved.</p>
                </li>
                
            </ul>
        </div>

        <div class="d-flex justify-content-end align-items-center flex-0">
            <p class="mb-0">Contact with us: </p>
            <div class="ml-3">
                <%= my_icon("twitter", class: "social-icons") %>
                <%= my_icon("instagram", class: "social-icons") %>
                <%= my_icon("facebook", class: "social-icons") %>
            </div>
        </div>
       
        
    </div>


</div>
<% end %>

<footer class="d-flex justify-content-between px-3 align-items-center py-2 footer">
    <div class="logo flex-1 w-25">
        <%= link_to "herSTYLE", root_path, class: "navbar-brand" %>
    </div>
    <div class="category-links flex-2 w-50">
        <ul class="w-100 d-flex align-items-center justify-content-center mb-0">
            <li class="">
                    <%= link_to "Privacy Policy", root_path %>
                </li>
                <li class="pl-2">
                    <%= link_to "Terms & Conditions", root_path %>
                </li>
                <li class="pl-3">
                    <p class="mb-0 copyright-text">Copyright 2020. All right reserved.</p>
                </li>
                
        </ul>
    </div>
    <div class="nav-right-links flex-1 w-25 d-flex justify-content-end align-items-center ">
        <p class="mb-0 contact-text">Connect with us: </p>
            <div class="ml-3">
                <%= my_icon("twitter-2", class: "social-icons mr-2") %>
                <%= my_icon("instagram-2", class: "social-icons mr-2") %>
                <%= my_icon("facebook-2", class: "social-icons") %>
            </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="d-flex justify-content-between px-3 align-items-center py-3 header">
    <div class="logo">
        <%= link_to "herSTYLE", root_path, class: "navbar-brand" %>
    </div>
    <div class="category-links">
        <ul class="w-100 d-flex align-items-center justify-content-center mb-0">
            <li class="py-1">
                <%= nav_link_to "Home", root_path %>
            </li>
            <% all_routes.each do |route| %>
            <li class="pl-3 py-1">
                <%= route %>
            </li>
            <% end %>

            <li class="py-1 ml-3">
                     <%= nav_link_to "New Category", new_category_path %>
            </li>
                          
        </ul>
    </div>
    <div class="nav-right-links">
        <ul class="d-flex align-items-center mb-0 justify-content-end">
            <% if current_user %>
                <li class="py-1 mr-2">
                    <%= link_to current_user.name, current_user %>
                </li>
                <li class="py-1 mx-3">
                     <%= nav_link_to "Write an Article", new_article_path %>
                </li>
                <li class="py-1">
                     <%= link_to "Sign Out", session_path, method: :delete %>
                </li>
                       

                
                
            <% else %>
                <li class="py-1 mr-3">
                     <%= link_to "Write an Article", new_article_path %>
                </li>
                <li class="py-1"><%= nav_link_to "Login |", signin_path %></li>
                <li class=" pl-1 py-1"><%= nav_link_to "Register", signup_path %></li>
            <% end %>
            </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HerStyle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
    
    
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="flash-messages ml-3">
      <%= render "layouts/flash" %>
    </div>
   
    <main class="main">
       
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>